### ISSUE TITLE
Server relative urls must start with SPWeb.ServerRelativeUrl

### ISSUE THREAD

**Issue by ParkJoongwoo** [sjultra/Push2Sharepoint#1]
Hi.

I tried to use your workflow, but I got an error like below.
```
Traceback (most recent call last):
  File "action/Push2Sharepoint.py", line 35, in <module>
    ctx.execute_query()
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/office365/runtime/client_runtime_context.py", line 141, in execute_query
    self.get_pending_request().execute_query()
  File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/office365/runtime/client_request.py", line 70, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('-2147024809, System.ArgumentException', 'Server relative urls must start with SPWeb.ServerRelativeUrl', "400 Client Error: Bad Request for url: https://mysite.sharepoint.com/sites/mysite-heatmap/_api/Web/getFolderByServerRelativeUrl('%2FUsers%2Frunner%2Fwork%2Fheatmap%2Fheatmap%2FShared')/Files/add(overwrite=true,url='heatmap')")
```
Here is my input information. 
```
username: ${{ secrets.SP_ACCOUNT }}
password: ${{ secrets.SP_PASSWORD }}
file_name: 'dist/heatmap'
full_url: 'https://mysite.sharepoint.com/sites/mysite-heatmap'
target_subfolder: 'Shared Documents/heatmap'
```
I guess this error could be due to below part.
```
# Define the base target folder as the current working directory
targetfolder = os.getcwd() + "/"

if len(targetsubfolder) != 0:
    targetfolder = targetfolder + targetsubfolder
```
Could you check this please?  

Thank you.

**Comment by TaEduard** [comment]
Hi!
@ParkJoongwoo  did you manage to get the action to work? 
Sorry for the slow response, this is an opensource pet project for me and I am doing my best to attend to all the things going on. 
I had in plan to take another stab at it over the next few days.
